🚀 Add support for file system sockets
Was trying to use sockfilter in a large django application that uses
SysLogHandler, https://hg.python.org/cpython/file/2.7/Lib/logging/handlers.py#l740

In that case, socket.connect() receives a string, so sockfilter was
throwing:

  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
      '%r: %s' % (name, e))
      ValueError: Unable to configure handler 'somehandler': __new__()
      takes exactly 3 arguments (9 given)

This commit also includes some changes to tests to reflect some changes
with ssl in python.